e_commerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

main/urls.py
from django.urls import path
from main.views import show_main, create_product, show_xml, show_xml_by_id, show_json, show_json_by_id, register, login_user, logout_user, edit_product, delete_product, show_profile_page, show_about_page, add_product_ajax

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create_product', create_product, name='create_product'),
    path('create_ajax', add_product_ajax, name='add_product_ajax'),
    path('xml/', show_xml, name='show_xml'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/', show_json, name='show_json'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-product/<uuid:id>', edit_product, name='edit_product'),
    path('delete-product/<uuid:id>', delete_product, name='delete_product'),
    path('profile/', show_profile_page, name='profile'),
    path('about/', show_about_page, name='about')
]

main/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=30)
    description = models.TextField()
    price = models.IntegerField()
    stock = models.IntegerField(default=0)
    category = models.CharField(max_length=30, default='Uncategorized')

main/forms.py
from django import forms
from main.models import Product
from django.utils.html import strip_tags

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["name", "price", "description", "stock", "category"]

    def clean_name(self):
        name = strip_tags(self.cleaned_data.get('name', ''))
        if not name.strip():
            raise forms.ValidationError('This field cannot be blank.')
        return name

    def clean_description(self):
        description = strip_tags(self.cleaned_data.get('description', ''))
        if not description.strip():
            raise forms.ValidationError('This field cannot be blank.')
        return description

    def clean_price(self):
        price = self.cleaned_data.get('price')
        if not price:
            raise forms.ValidationError('This field cannot be blank.')
        return price

    def clean_stock(self):
        stock = self.cleaned_data.get('stock')
        if not stock:
            raise forms.ValidationError('This field cannot be blank.')
        return stock

    def clean_category(self):
        category = strip_tags(self.cleaned_data.get('category', ''))
        if not category.strip():
            raise forms.ValidationError('This field cannot be blank.')
        return category

main/views.py
import datetime
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.core import serializers
from django.shortcuts import render, redirect, reverse
from main.forms import ProductForm
from main.models import Product
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.utils.html import strip_tags

# Create your views here.
@login_required(login_url='/login')
def show_main(request):
    context = {
        'username' : request.user.username,
        'npm' : '2306152153',
        'nama': 'Priscilla Natanael Surjanto',
        'kelas': 'PBP F',
        'last_login': request.COOKIES['last_login']
    }

    return render(request, "main.html", context)

def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return redirect('main:show_main')

    context = {'form': form}
    return render(request, "create_product.html", context)

@csrf_exempt
@require_POST
def add_product_ajax(request):
    name = strip_tags(request.POST.get("name"))
    description = strip_tags(request.POST.get("description"))
    price = strip_tags(request.POST.get("price"))
    stock = strip_tags(request.POST.get("stock"))
    category = strip_tags(request.POST.get("category"))
    user = request.user

    new_product = Product(
        name=name, 
        description=description, 
        price=price, 
        stock=stock, 
        category=category, 
        user=user
    )

    if name == "" or description == "" or price == "" or stock == "" or category == "":
        messages.error(request, "Please fill all the fields")
        return HttpResponse(b"BAD REQUEST", status=400)
    else:
        new_product.save()

    return HttpResponse(b"CREATED", status=201)

def show_xml(request):
    data = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
   if request.method == 'POST':
      form = AuthenticationForm(data=request.POST)

      if form.is_valid():
        user = form.get_user()
        login(request, user)
        response = HttpResponseRedirect(reverse("main:show_main"))
        response.set_cookie('last_login', str(datetime.datetime.now()))
        return response
      else:
        messages.error(request, "Invalid username or password. Please try again.")

   else:
      form = AuthenticationForm(request)
   context = {'form': form}
   return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def edit_product(request, id):
    # Get mood entry berdasarkan id
    product = Product.objects.get(pk = id)

    # Set mood entry sebagai instance dari form
    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_product.html", context)

def delete_product(request, id):
    # Get mood berdasarkan id
    product = Product.objects.get(pk = id)
    # Hapus mood
    product.delete()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('main:show_main'))

def show_profile_page(request):
    context = {
        'username' : request.user.username,
        'last_login': request.COOKIES['last_login']
    }

    return render(request, "profile_info.html", context)

def show_about_page(request):
    context = {
        'npm' : '2306152153',
        'nama': 'Priscilla Natanael Surjanto',
        'kelas': 'PBP F'
    }

    return render(request, "store_info.html", context)

main/templates/card_info.html
<div class="bg-orange-400 rounded-xl overflow-hidden border-2 border-indigo-800">
    <div class="p-4 animate-shine">
      <h5 class="text-lg font-semibold text-gray-200">{{ title }}</h5>
      <p class="text-white">{{ value }}</p>
    </div>
</div>

main/templates/card_product.html
<div class="relative break-inside-avoid">
    <div class="relative top-5 bg-amber-100 shadow-md rounded-lg mb-6 break-inside-avoid flex flex-col border-2 border-indigo-300 transform rotate-1 hover:rotate-0 transition-transform duration-300">
      <div class="bg-amber-200 text-blue-500 p-4 rounded-t-lg border-b-2 border-blue-400">
        <div class="flex justify-right items-center">
          <h3 class="font-bold text-xl mb-2">{{product.name}}</h3>
          <span class="ml-4 mb-2 font-semibold inline-block py-1 px-2 rounded-full text-amber-500 bg-orange-100">
            Rp. {{ product.price }}
          </span>
        </div>
      </div>
      <div class="p-4">
        <p class="font-semibold text-s mb-2 text-blue-400">Description</p> 
        <p class="text-gray-700 mb-2">
          <span class="bg-[linear-gradient(to_bottom,transparent_0%,transparent_calc(100%_-_1px),#CDC1FF_calc(100%_-_1px))] bg-[length:100%_1.5rem] pb-1 text-blue-500">{{product.description}}</span>
        </p>
        <div class="mt-4">
          <div class="relative pt-1">
            <div class="flex mb-2 items-center justify-between">
              <div class="flex justify-right items-center">
                <span class="text-xs font-semibold inline-block py-1 px-2 rounded-full text-white bg-yellow-300">
                  Stock: {{ product.stock }}
                </span>
                <span class="ml-2 text-xs font-semibold inline-block py-1 px-2 rounded-full text-white bg-yellow-300">
                  {{ product.category }}
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="absolute top-0 -right-4 flex space-x-1">
      <a href="{% url 'main:edit_product' product.pk %}" class="bg-yellow-500 hover:bg-yellow-600 text-white rounded-full p-2 transition duration-300 shadow-md">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-9 w-9" viewBox="0 0 20 20" fill="currentColor">
          <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
        </svg>
      </a>
      <a href="{% url 'main:delete_product' product.pk %}" class="bg-red-500 hover:bg-red-600 text-white rounded-full p-2 transition duration-300 shadow-md">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-9 w-9" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
        </svg>
      </a>
    </div>
  </div>

main/templates/create_product.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Create Product</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}

<div class="flex flex-col min-h-screen bg-gray-100">
  <div class="container mx-auto px-4 py-8 mt-16 max-w-xl">
    <h1 class="text-3xl font-bold text-center mb-8 text-blue-500">Create Product</h1>
  
    <div class="bg-yellow-200 shadow-md rounded-lg p-6 form-style">
      <form method="POST" class="space-y-6">
        {% csrf_token %}
        {% for field in form %}
          <div class="flex flex-col">
            <label for="{{ field.id_for_label }}" class="mb-2 font-semibold text-blue-500">
              {{ field.label }}
            </label>
            <div class="w-full">
              {{ field }}
            </div>
            {% if field.help_text %}
              <p class="mt-1 text-sm text-gray-500">{{ field.help_text }}</p>
            {% endif %}
            {% for error in field.errors %}
              <p class="mt-1 text-sm text-red-600">{{ error }}</p>
            {% endfor %}
          </div>
        {% endfor %}
        <div class="flex justify-center mt-6">
          <button type="submit" class="bg-blue-500 text-white font-semibold px-6 py-3 rounded-lg hover:bg-blue-600 transition duration-300 ease-in-out w-full">
            Create Product
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

main/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Cilla's Minimart</title>
<script src="https://cdn.jsdelivr.net/npm/dompurify@3.1.7/dist/purify.min.js"></script>
{% endblock meta %}
{% block content %}
{% include 'navbar.html' %}
<div class="overflow-x-hidden px-4 md:px-8 pb-8 pt-24 min-h-screen bg-gray-100 flex flex-col">
    <div id="product_cards"></div>
    <div id="crudModal" tabindex="-1" aria-hidden="true" class="hidden fixed inset-0 z-50 w-full flex items-center justify-center bg-gray-800 bg-opacity-50 overflow-x-hidden overflow-y-auto transition-opacity duration-300 ease-out">
        <div id="crudModalContent" class="relative bg-yellow-200 rounded-lg shadow-lg w-5/6 sm:w-3/4 md:w-1/2 lg:w-1/3 mx-4 sm:mx-auto p-6 transform scale-95 opacity-0 transition-transform transition-opacity duration-300 ease-out overflow-y-auto max-h-[80vh]">
          <!-- Modal header -->
          <div class="flex items-center justify-between p-4 border-b rounded-t">
            <h3 class="text-xl font-bold text-blue-500">
              Add New Product by AJAX
            </h3>
            <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center" id="closeModalBtn">
              <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
              </svg>
              <span class="sr-only">Close modal</span>
            </button>
          </div>
          <!-- Modal body -->
          <div class="px-6 py-4 space-y-6 form-style">
            <form id="productForm">
              <div class="mb-4">
                <label for="name" class="block text-sm font-medium text-blue-400">Name</label>
                <input type="text" id="name" name="name" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-indigo-700" placeholder="Enter product name" required>
              </div>
              <div class="mb-4">
                <label for="description" class="block text-sm font-medium text-blue-400">Description</label>
                <textarea id="description" name="description" rows="3" class="mt-1 block w-full h-52 resize-none border border-gray-300 rounded-md p-2 hover:border-indigo-700" placeholder="Describe your product" required></textarea>
              </div>
              <div class="mb-4">
                <label for="price" class="block text-sm font-medium text-blue-400">Price</label>
                <input type="number" id="price" name="price" min="1000" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-indigo-700" required>
              </div>
              <div class="mb-4">
                <label for="stock" class="block text-sm font-medium text-blue-400">Stock</label>
                <input type="number" id="stock" name="stock" min="1" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-indigo-700" required>
              </div>
              <div class="mb-4">
                <label for="category" class="block text-sm font-medium text-blue-400">Category</label>
                <input type="text" id="category" name="category" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-indigo-700" required>
              </div>
            </form>
          </div>
          <!-- Modal footer -->
          <div id="error-message" class="text-red-500 text-center"></div>
          <div class="flex flex-col space-y-2 md:flex-row md:space-y-0 md:space-x-2 p-6 border-t border-gray-200 rounded-b justify-center md:justify-end">
            <button type="button" class="bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded-lg" id="cancelButton">Cancel</button>
            <button type="submit" id="submitProduct" form="productForm" class="bg-indigo-700 hover:bg-indigo-600 text-white font-bold py-2 px-4 rounded-lg">Save</button>
          </div>
        </div>
      </div>
</div>
<script>
    function addProduct() {
        event.preventDefault();
        document.getElementById("error-message").innerHTML = "";
        fetch("{% url 'main:add_product_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#productForm')),
            headers: {
                'X-CSRFToken': '{{ csrf_token }}'
            }
        })
        .then(response => {
            if (response.ok) {
                document.getElementById("productForm").reset();
                hideModal();
                refreshProducts();
            } else {
                document.getElementById("productForm").reset();
                return response.text().then(text => {
                    document.getElementById("error-message").innerHTML = '<p>Please fill out all fields correctly.</p>';
                });
            }
        })
        document.querySelector("[data-modal-toggle='crudModal']").click();
        return false;
    }

    async function getProducts(){
        return fetch("{% url 'main:show_json' %}").then((res) => res.json())
    }

    async function refreshProducts() {
    document.getElementById("product_cards").innerHTML = "";
    document.getElementById("product_cards").className = "";
    const products = await getProducts();
    let htmlString = "";
    let classNameString = "";

    if (products.length === 0) {
        classNameString = "flex flex-col items-center justify-center min-h-[24rem] p-6";
        htmlString = `
            <div class="flex flex-col items-center justify-center min-h-[24rem] p-6">
                <img src="{% static 'image/sedih-banget.png' %}" alt="Sad face" class="w-32 h-32 mb-2"/>
                <p class="text-center text-gray-600">Belum ada barang yang tersedia.</p>
                <a href="{% url 'main:create_product' %}" class="bg-yellow-400 hover:bg-yellow-500 text-white font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-105 mx-4 mt-2 mb-2">
                    Add New Product
                </a>
                <button data-modal-target="crudModal" data-modal-toggle="crudModal" class="btn bg-blue-400 hover:bg-blue-500 text-white font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-105" onclick="showModal();">
                Add New Product by AJAX
                </button>
            </div>
        `;
    }
    else {
        classNameString = "flex flex-col"
        htmlString += `
            <div class="flex flex-col sm:flex-row justify-between items-center w-full mb-6 space-y-4 sm:space-y-0">
                <p class="text-2xl text-yellow-500 font-bold">Shop</p>
                <div class="flex flex-col sm:flex-row space-y-4 sm:space-y-0 sm:space-x-4 w-full sm:w-auto">
                    <a href="{% url 'main:create_product' %}" class="w-full sm:w-auto bg-yellow-400 hover:bg-yellow-500 text-white font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-105 text-center">
                        Add New Product
                    </a>
                    <button data-modal-target="crudModal" data-modal-toggle="crudModal" class="w-full sm:w-auto bg-blue-400 hover:bg-blue-500 text-white font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-105 text-center" onclick="showModal();">
                        Add New Product by AJAX
                    </button>
                </div>
            </div>
            <div class="columns-1 sm:columns-2 lg:columns-3 gap-6 space-y-6 w-full">
            `;
        products.forEach((item) => {
            const name = DOMPurify.sanitize(item.fields.name);
            const description= DOMPurify.sanitize(item.fields.description);
            const price = DOMPurify.sanitize(item.fields.price);
            const stock = DOMPurify.sanitize(item.fields.stock);
            const category = DOMPurify.sanitize(item.fields.category);
            htmlString += `
            <div class="relative break-inside-avoid">
                <div class="relative top-5 bg-amber-100 shadow-md rounded-lg mb-6 break-inside-avoid flex flex-col border-2 border-indigo-300 transform rotate-1 hover:rotate-0 transition-transform duration-300">
                <div class="bg-amber-200 text-blue-500 p-4 rounded-t-lg border-b-2 border-blue-400">
                    <div class="flex justify-right items-center">
                    <h3 class="font-bold text-xl mb-2">${item.fields.name}</h3>
                    <span class="ml-4 mb-2 font-semibold inline-block py-1 px-2 rounded-full text-amber-500 bg-orange-100">
                        Rp. ${item.fields.price}
                    </span>
                    </div>
                </div>
                <div class="p-4">
                    <p class="font-semibold text-s mb-2 text-blue-400">Description</p> 
                    <p class="text-gray-700 mb-2">
                    <span class="bg-[linear-gradient(to_bottom,transparent_0%,transparent_calc(100%_-_1px),#CDC1FF_calc(100%_-_1px))] bg-[length:100%_1.5rem] pb-1 text-blue-500">${item.fields.description}</span>
                    </p>
                    <div class="mt-4">
                    <div class="relative pt-1">
                        <div class="flex mb-2 items-center justify-between">
                        <div class="flex justify-right items-center">
                            <span class="text-xs font-semibold inline-block py-1 px-2 rounded-full text-white bg-yellow-300">
                            Stock: ${item.fields.stock}
                            </span>
                            <span class="ml-2 text-xs font-semibold inline-block py-1 px-2 rounded-full text-white bg-yellow-300">
                            ${item.fields.category}
                            </span>
                        </div>
                        </div>
                    </div>
                    </div>
                </div>
                </div>
                <div class="absolute top-0 -right-4 flex space-x-1">
                    <a href="/edit-product/${item.pk}" class="bg-yellow-500 hover:bg-yellow-600 text-white rounded-full p-2 transition duration-300 shadow-md">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-9 w-9" viewBox="0 0 20 20" fill="currentColor">
                            <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
                        </svg>
                    </a>
                    <a href="/delete-product/${item.pk}" class="bg-red-500 hover:bg-red-600 text-white rounded-full p-2 transition duration-300 shadow-md">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-9 w-9" viewBox="0 0 20 20" fill="currentColor">
                            <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
                        </svg>
                    </a>
                </div>
            </div>
            `;
        })
        
        htmlString += `</div>`;
    }
    document.getElementById("product_cards").className = classNameString;
    document.getElementById("product_cards").innerHTML = htmlString;
}
refreshProducts();

const modal = document.getElementById('crudModal');
const modalContent = document.getElementById('crudModalContent');

function showModal() {
    const modal = document.getElementById('crudModal');
    const modalContent = document.getElementById('crudModalContent');

    modal.classList.remove('hidden'); 
    setTimeout(() => {
    modalContent.classList.remove('opacity-0', 'scale-95');
    modalContent.classList.add('opacity-100', 'scale-100');
    }, 50); 
}

function hideModal() {
    const modal = document.getElementById('crudModal');
    const modalContent = document.getElementById('crudModalContent');

    modalContent.classList.remove('opacity-100', 'scale-100');
    modalContent.classList.add('opacity-0', 'scale-95');

    setTimeout(() => {
    modal.classList.add('hidden');
    }, 150); 
}

document.getElementById("cancelButton").addEventListener("click", hideModal);
document.getElementById("closeModalBtn").addEventListener("click", hideModal);

document.getElementById("productForm").addEventListener("submit", (e) => {
    e.preventDefault();
    addProduct();
  })
</script>
{% endblock content %}

templates/navbar.html
{% load static %}
<nav class="bg-yellow-200 shadow-lg fixed top-0 left-0 z-40 w-screen">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between h-16">
      <div class="flex items-center">
        <!-- Logo -->
        <img src="{% static 'image/store-logo.png' %}" alt="Logo" class="h-8 w-8 mr-4">
        <h1 class="text-2xl font-serif font-bold text-center text-blue-400">Cilla's Minimart</h1>
      </div>

      <!-- Desktop navigation links (shown on medium screens and larger) -->
      <div class="hidden md:flex items-center space-x-4">
        <a href="{% url 'main:show_main' %}" class="text-blue-500 hover:text-blue-700 font-bold">Shop</a>
        <a href="{% url 'main:about' %}" class="text-blue-500 hover:text-blue-700 font-bold">About Us</a>
        <a href="{% url 'main:profile' %}" class="text-blue-500 hover:text-blue-700 font-bold">Profile</a>
        {% if user.is_authenticated %}
          <span class="text-orange-500 mr-4">Welcome, {{ user.username }}</span>
          <a href="{% url 'main:logout' %}" class="text-center bg-red-400 hover:bg-red-600 text-white font-bold py-2 px-4 rounded transition duration-300">
            Logout
          </a>
        {% else %}
          <a href="{% url 'main:login' %}" class="text-center bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded transition duration-300 mr-2">
            Login
          </a>
          <a href="{% url 'main:register' %}" class="text-center bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded transition duration-300">
            Register
          </a>
        {% endif %}
      </div>

      <!-- Mobile menu button (only shown on small screens) -->
      <div class="md:hidden flex items-center">
        <button class="mobile-menu-button">
          <svg class="w-6 h-6 text-black" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
            <path d="M4 6h16M4 12h16M4 18h16"></path>
          </svg>
        </button>
      </div>
    </div>
  </div>

  <!-- Mobile menu (shown when hamburger is clicked) -->
  <div class="mobile-menu hidden md:hidden px-4 w-full">
    <div class="pt-2 pb-3 space-y-1 mx-auto">
      <a href="{% url 'main:show_main' %}" class="block text-blue-500 hover:text-blue-700 font-bold py-2">Shop</a>
      <a href="{% url 'main:about' %}" class="block text-blue-500 hover:text-blue-700 font-bold py-2">About Us</a>
      <a href="{% url 'main:profile' %}" class="block text-blue-500 hover:text-blue-700 font-bold py-2">Profile</a>
      {% if user.is_authenticated %}
        <span class="block text-blue-500 px-3 py-2">Welcome, {{ user.username }}</span>
        <a href="{% url 'main:logout' %}" class="block text-center bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded transition duration-300">
          Logout
        </a>
      {% else %}
        <a href="{% url 'main:login' %}" class="block text-center bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded transition duration-300 mb-2">
          Login
        </a>
        <a href="{% url 'main:register' %}" class="block text-center bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded transition duration-300">
          Register
        </a>
      {% endif %}
    </div>
  </div>

  <script>
    const btn = document.querySelector("button.mobile-menu-button");
    const menu = document.querySelector(".mobile-menu");

    btn.addEventListener("click", () => {
      menu.classList.toggle("hidden");
    });
  </script>
</nav>